In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
handle = df['Age'].mean()

In [ ]:
handle

np.float64(30.272590361445783)

In [ ]:
df.Age= df.Age.fillna(handle)

In [ ]:
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex       Age  SibSp  \
0                                Kelly, Mr. James    male  34.50000      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.00000      1   
2                       Myles, Mr. Thomas Francis    male  62.00000      0   
3                                Wirz, Mr. Albert    male  27.00000      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1   
..                                            ...     ...       ...    ...   
413                            Spector, Mr. Woolf    male  30.27259      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.00000      0   
415                  Saether, Mr. Simon Sivertsen    male  38.50000      0   
416                           Ware, Mr. Frederick    male  30.27259      0   
417                      Peter, Master. Michael J    male  30.27259      1   

     Parch              Ticket      Fare Cabin Embarked  
0        0              330911    7.8292   NaN        Q  
1        0              363272    7.0000   NaN        S  
2        0              240276    9.6875   NaN        Q  
3        0              315154    8.6625   NaN        S  
4        1             3101298   12.2875   NaN        S  
..     ...                 ...       ...   ...      ...  
413      0           A.5. 3236    8.0500   NaN        S  
414      0            PC 17758  108.9000  C105        C  
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0              359309    8.0500   NaN        S  
417      1                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [ ]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis ='columns',inplace= True)

KeyError: "['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'] not found in axis"

In [ ]:
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [ ]:
# 1 - survived 0 - not survived
inputs= df.drop('Survived', axis = 'columns')
target = df.Survived

In [ ]:
dummies = pd.get_dummies(df['Sex'])

In [ ]:
dummies = dummies.astype(int)
# will display o and 1 instead of True and False

In [ ]:
dummies

female  male
0         0     1
1         1     0
2         0     1
3         0     1
4         1     0
..      ...   ...
413       0     1
414       1     0
415       0     1
416       0     1
417       0     1

[418 rows x 2 columns]

In [ ]:
df

Survived  Pclass     Sex       Age      Fare
0           0       3    male  34.50000    7.8292
1           1       3  female  47.00000    7.0000
2           0       2    male  62.00000    9.6875
3           0       3    male  27.00000    8.6625
4           1       3  female  22.00000   12.2875
..        ...     ...     ...       ...       ...
413         0       3    male  30.27259    8.0500
414         1       1  female  39.00000  108.9000
415         0       3    male  38.50000    7.2500
416         0       3    male  30.27259    8.0500
417         0       3    male  30.27259   22.3583

[418 rows x 5 columns]

In [ ]:
inputs

Pclass     Sex       Age      Fare
0         3    male  34.50000    7.8292
1         3  female  47.00000    7.0000
2         2    male  62.00000    9.6875
3         3    male  27.00000    8.6625
4         3  female  22.00000   12.2875
..      ...     ...       ...       ...
413       3    male  30.27259    8.0500
414       1  female  39.00000  108.9000
415       3    male  38.50000    7.2500
416       3    male  30.27259    8.0500
417       3    male  30.27259   22.3583

[418 rows x 4 columns]

In [ ]:
inputs = inputs.drop(['Sex'] ,axis='columns')

In [ ]:
inputs

Pclass       Age      Fare
0         3  34.50000    7.8292
1         3  47.00000    7.0000
2         2  62.00000    9.6875
3         3  27.00000    8.6625
4         3  22.00000   12.2875
..      ...       ...       ...
413       3  30.27259    8.0500
414       1  39.00000  108.9000
415       3  38.50000    7.2500
416       3  30.27259    8.0500
417       3  30.27259   22.3583

[418 rows x 3 columns]

In [ ]:
df

Survived  Pclass     Sex       Age      Fare
0           0       3    male  34.50000    7.8292
1           1       3  female  47.00000    7.0000
2           0       2    male  62.00000    9.6875
3           0       3    male  27.00000    8.6625
4           1       3  female  22.00000   12.2875
..        ...     ...     ...       ...       ...
413         0       3    male  30.27259    8.0500
414         1       1  female  39.00000  108.9000
415         0       3    male  38.50000    7.2500
416         0       3    male  30.27259    8.0500
417         0       3    male  30.27259   22.3583

[418 rows x 5 columns]

In [ ]:
inputs

Pclass       Age      Fare
0         3  34.50000    7.8292
1         3  47.00000    7.0000
2         2  62.00000    9.6875
3         3  27.00000    8.6625
4         3  22.00000   12.2875
..      ...       ...       ...
413       3  30.27259    8.0500
414       1  39.00000  108.9000
415       3  38.50000    7.2500
416       3  30.27259    8.0500
417       3  30.27259   22.3583

[418 rows x 3 columns]

In [ ]:
merged = pd.concat([inputs,dummies],axis = 'columns')

In [ ]:
merged

Pclass       Age      Fare  female  male
0         3  34.50000    7.8292       0     1
1         3  47.00000    7.0000       1     0
2         2  62.00000    9.6875       0     1
3         3  27.00000    8.6625       0     1
4         3  22.00000   12.2875       1     0
..      ...       ...       ...     ...   ...
413       3  30.27259    8.0500       0     1
414       1  39.00000  108.9000       1     0
415       3  38.50000    7.2500       0     1
416       3  30.27259    8.0500       0     1
417       3  30.27259   22.3583       0     1

[418 rows x 5 columns]

In [ ]:
final = merged.drop(['male'],axis ='columns')

In [ ]:
final

Pclass       Age      Fare  female
0         3  34.50000    7.8292       0
1         3  47.00000    7.0000       1
2         2  62.00000    9.6875       0
3         3  27.00000    8.6625       0
4         3  22.00000   12.2875       1
..      ...       ...       ...     ...
413       3  30.27259    8.0500       0
414       1  39.00000  108.9000       1
415       3  38.50000    7.2500       0
416       3  30.27259    8.0500       0
417       3  30.27259   22.3583       0

[418 rows x 4 columns]

In [ ]:
final.columns[final.isna().any()]

Index(['Fare'], dtype='object')

In [ ]:
null_count_city = df['Fare'].isnull().sum()
print(f"Number of null values in 'Fare' column: {null_count_city}")

Number of null values in 'Fare' column: 1


In [ ]:
final.Fare[:50]

0       7.8292
1       7.0000
2       9.6875
3       8.6625
4      12.2875
5       9.2250
6       7.6292
7      29.0000
8       7.2292
9      24.1500
10      7.8958
11     26.0000
12     82.2667
13     26.0000
14     61.1750
15     27.7208
16     12.3500
17      7.2250
18      7.9250
19      7.2250
20     59.4000
21      3.1708
22     31.6833
23     61.3792
24    262.3750
25     14.5000
26     61.9792
27      7.2250
28     30.5000
29     21.6792
30     26.0000
31     31.5000
32     20.5750
33     23.4500
34     57.7500
35      7.2292
36      8.0500
37      8.6625
38      9.5000
39     56.4958
40     13.4167
41     26.5500
42      7.8500
43     13.0000
44     52.5542
45      7.9250
46     29.7000
47      7.7500
48     76.2917
49     15.9000
Name: Fare, dtype: float64

In [ ]:
final.Fare = final.Fare.fillna(final.Fare.mean())
final.head()

Pclass   Age     Fare  female
0       3  34.5   7.8292       0
1       3  47.0   7.0000       1
2       2  62.0   9.6875       0
3       3  27.0   8.6625       0
4       3  22.0  12.2875       1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(final, target, test_size = 0.30, random_state =1)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB ()

In [ ]:
model.fit(xtrain, ytrain)

GaussianNB()

In [ ]:
model.score(xtest,ytest)

1.0

In [ ]:
xtest[:10]

Pclass       Age     Fare  female
358       3  30.27259   7.7500       0
164       2  41.00000  13.0000       0
17        3  21.00000   7.2250       0
67        1  47.00000  42.4000       0
4         3  22.00000  12.2875       1
377       2  21.00000  11.5000       0
214       3  38.00000   7.7750       1
290       1  30.27259  39.6000       0
381       3  26.00000   7.8792       0
5         3  14.00000   9.2250       0

In [ ]:
ytest[0:10]

358    0
164    0
17     0
67     0
4      1
377    0
214    1
290    0
381    0
5      0
Name: Survived, dtype: int64

In [ ]:
model.predict(xtest[0:10])

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0])

In [ ]:
model.predict_proba(xtest[:10])

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
#pclass, Age, Fare, Gender
test = [[1,23.000000,113.2750,0]]
#test = xtest
a= model.predict(test)
if a[0] == 0:
    print("Not Survived")
else:
    print(" Survived")

Not Survived


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score (GaussianNB(),xtrain,ytrain,cv = 5)

array([1., 1., 1., 1., 1.])